config/routes.rb
Rails.application.routes.draw do

  get 'search', to: 'search#search'
  
  get 'auth/:provider/callback', to: 'sessions#create_from_omniauth'

  resource :home, only: [:index]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users, controller: 'users', only: 'create'
  resources :listings do
    resources :reservations, only: [:create, :destroy]
  end

  get 'tags/:tag', to: 'listings#index', as: :tag
  post "/filter_listings", to: 'listings#price_range', as: 'filter_listings'

  root 'home#index'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/listing.rb
require 'elasticsearch/model'

class Listing < ActiveRecord::Base

	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  mount_uploaders :images, ImageUploader

	belongs_to :user
  has_many :reservations, :dependent => :destroy
end

# Listing.__elasticsearch__.create_index!
Listing.import # for auto sync model with elastic search

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing

	def overlaps?(other_reservation)
    (self.checkin - other_reservation.checkout) * (other_reservation.checkin - self.checkout) >= 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  mount_uploader :avatar, AvatarUploader

  has_many :listings, :dependent => :destroy
  has_many :authentications, :dependent => :destroy
  has_many :reservations, :dependent => :destroy
  validates :email, uniqueness: true, presence: true

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.avatar = auth_hash["info"]["image"]
      u.authentications<<(authentication)
    end
  end
  
  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end
  
  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@listings = Listing.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index
		if params[:tag]
			@listings = Listing.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
		elsif params[:search]
			@listings = Listing.where(location: params[:search].downcase).paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
		else
			@listings = current_user.listings.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
		end
	end

	def new
		if current_user
			@listing = Listing.new
		else
			redirect_to sign_in_path, notice: "Please sign in to continue." and return
		end
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to @listing, notice: "Listing created."
		else
			render 'new'
		end
	end

	def show
		@listing = Listing.find(params[:id])
		@reservation = Reservation.new
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])
		if @listing.update(listing_params)
			redirect_to @listing, notice: "Success!"
		else
			render 'edit'
		end
	end

	def destroy
    Listing.find(params[:id]).destroy
    flash[:success] = "Listing deleted"
    redirect_to listings_path
  end

  def price_range
		@listings = Listing.where(location: params[:location])
		
		params[:from] = "0" if params[:from] == ""
		params[:to] = "10000" if params[:to] == ""
		
		@listings = @listings.where("price >= ? and price <= ?", params[:from], params[:to]).paginate(:page => params[:page], :per_page => 6).order('price ASC')

		respond_to do |format|
		  format.js
		end
	end

	private

		def listing_params
			params[:listing][:location].downcase!
			params.require(:listing).permit(:title, :description, :home_type, :location, :guest, :bedroom, :price, {images: []}, :tag_list, :breakfast)
		end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
  	if !current_user.nil?
	  	@listing = Listing.find(params[:listing_id])
	  	@reservation = Reservation.new
	  	reservation = Reservation.new(reservation_params)
	  	reservation.user_id = current_user.id
	  	reservation.listing_id = params[:listing_id]
	  	
	  	if !@listing.reservations.all.empty?
		  	@listing.reservations.all.each do |other|
		  	
		  		if reservation.overlaps?(other)
		  			redirect_to listings_path, notice: "Date unavailable." && return
		  		end
		  	end
		  end
	  	
	  	if reservation.save
	  		# ReservationJob.perform_later(current_user, @listing.user, reservation.id)
		  	redirect_to @listing, notice: "Success!"
		  else
			  redirect_to @listing, notice: "Unable to book a reservation."
			end
		else
			redirect_to sign_in_path, notice: "Please sign in to continue."
		end
  end

  def destroy
  	reservation = Reservation.find(params[:id])
  	reservation.destroy
  	redirect_to listings_path
  end

private
	
		def reservation_params
			params.require(:reservation).permit(:checkin, :checkout)
		end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
	  if params[:q].nil?
	    @listings = []
	  else
	    @listings = Listing.search params[:q]
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]

    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = listings_path
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = edit_user_path(user)   
      @notice = "Success! Please update your details below."
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update, :destroy]

	def show
	end

	def edit
	end

	def create
		if match_password
	    @user = User.new(permit_params)
	    # @user.avatar = "default_avatar.png"

	    if @user.save #(permit_params)
	      sign_in @user
      	@notice = "Success! Please update your details below."
	      redirect_to edit_user_path(@user), :notice => @notice and return
	    end
		end
		render 'new'
		# redirect_to sign_up_path, :notice => "Password does not match!"
  end

  def update
    if @user.update_attributes(permit_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
	end

	def destroy
		@user.destroy
    flash[:success] = "User deleted"
    redirect_to root_path
	end

  private

		def find_user
			@user = User.find(params[:id])
		end

	  def permit_params
	    params.require(:user).permit(:name, :email, :encrypted_password, :password, :confirmation_token, :remember_token, :avatar, :location, :state, :country, :description)
	  end

	  def match_password
			true if params[:user][:password] = params[:user][:password_confirmation]
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		if user.id == session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def display_tags(listing)
		raw listing.tag_list.map { |tag| link_to tag, tag_path(tag)}.join(', ')
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<%= provide(:page, 'home') %>
<div class="fullscreen-bg">
	<%= video_tag(["waterbnb.webm", "waterbnb.mp4"], class: "fullscreen-bg__video", poster: "home_videoframe.png", autoplay: true, loop: true )%>
</div>
<div class="home-search center-content">
	<form action="<%= listings_path %>">
		<input type="text" class="form-control" placeholder="Where do you want to go?" style="width:60%;" name="search">
		<input type="submit" value="Search" class="btn btn-medium btn-pink">
	</form>
</div>
<!--div class="fb-like" data-share="true" data-width="450" data-show-faces="true"></div-->

<!-- <div class="fullscreen-clear"></div> -->

<div id="listing-container">
	<% if @listings %>
		<div id="listing-main" class="full-width">
			<% @listings.each do |listing| %>
				<div class="listing-item listing-item-home">
					<div class="listing-item-image">
						<%= link_to (image_tag listing.images[0]), listing_path(listing) %>
					</div>
					<div class="listing-item-title">
						<%= link_to listing.title[0..37].gsub(/\s\w+\s*$/,'...'), listing_path(listing) %>
					</div>
					<div class="listing-item-info">
						<div class="listing-location">
							<%= listing.home_type %> · <%= listing.location.titleize %> · <i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i>
						</div>
						<div class="listing-item-user">
							<a href="/users/<%= listing.user.id %>"><%= image_tag listing.user.avatar, class: 'listing-item-avatar' %></a>
						</div>
					</div>
				</div>
			<% end%>
		</div>
		<div class="digg_pagination">
	    <div class="page_info">
	      <%= page_entries_info @listings %>
	    </div>
	    <%= will_paginate @listings, :container => false, previous_label: "&#9664;", next_label: "&#9654;" %>
	  </div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vacation Rentals, Homes, Apartments & Rooms for Rent - Waterbnb</title>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if yield(:page) == 'home' %>
      <%= render 'nav/home_nav' %>
    <% else %>
      <%= render 'nav/nav' %>
    <% end %>
    
    <% if flash.presence %>
      <div id="flash">
        <%= image_tag 'notice_bubble.png' %>
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
    <% elsif @notice.presence %>
      <div id="flash">
        <%= image_tag 'notice_bubble.png' %>
        <% @notice.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
    <% end %>
    <% if yield(:banner).presence %>
      <div id="banner-<%= yield(:banner) %>" style="background: url(<%= yield(:banner_image) if !yield(:banner_image).nil? %>); background-size: cover; background-position: 100% 50%;">
      </div>
    <% else %>
      <br>
    <% end %>
    <div id="main-container">
      <%= yield %>
    </div>
    <div class="push"></div>
    <footer>
      <ul>
        <li>About Us</li>
        <li>Privacy</li>
        <li>Terms</li>
        <li>Contact Us</li>
        <li>Signup for newsletter</li>
      </ul>
    </footer>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, :html => { :multipart => true } do |f| %>
	<div class="form-container">
		<div class="form-header">
			New Listing
		</div>
	
		<div class="form-body">
			<%= render 'shared/error_messages', object: f.object %>
			<table class="full-width">
				<tr>
					<td class="form-label"><%= f.label :title %></td>
					<td class="form-box"><%= f.text_field :title, class: 'form-control full-width-92', placeholder: :title, required: true %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :home_type %></td>
					<td class="form-box"><%= f.text_field :home_type, class: 'form-control full-width-92', placeholder: :home_type, required: true %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :description %></td>
					<td class="form-box"><%= f.text_area :description, class: 'form-control full-width-92', placeholder: :description, required: true %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :location %></td>
					<td class="form-box"><%= f.text_field :location, class: 'form-control full-width-92', placeholder: :location%></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :guest %></td>
					<td class="form-box"><%= f.number_field :guest, class: 'form-control full-width-92', min: '0', placeholder: '0' %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :bedroom %></td>
					<td class="form-box"><%= f.number_field :bedroom, class: 'form-control full-width-92', min: '0', placeholder: '0' %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :tag_list, "Tags (saperate tags using commas)" %></td>
					<td class="form-box"><%= f.text_field :tag_list, class: 'form-control full-width-92' %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :price %></td>
					<td class="form-box"><%= f.text_field :price, class: 'form-control full-width-92', placeholder: :price %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :breakfast %></td>
					<td class="form-box"><%= f.check_box :breakfast, class: 'form-control form-check-box' %></td>
				</tr>
				<tr>
					<td class="form-label"><%= f.label :image %></td>
					<td class="form-box"><%= f.file_field :images, multiple: true, class: 'form-control full-width-92' %></td>
				</tr>
			</table>
		</div>
	</div>
	<%= f.submit 'Create', class: 'btn btn-block btn-large btn-pink center-layout'%>
<% end %>

app/views/listings/_listing_item.html.erb
<% @listings.each do |listing| %>
	<div class="listing-item">
		<div class="listing-item-image">
			<%= link_to (image_tag listing.images[0]), listing_path(listing) %>
		</div>
		<div class="listing-item-title">
			<%= link_to listing.title[0..37].gsub(/\s\w+\s*$/,'...'), listing_path(listing) %>
		</div>
		<div class="listing-item-info">
			<div class="listing-location">
				<%= listing.home_type %> · <%= listing.location.titleize %> · <i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i>
			</div>
			<div class="listing-item-user">
				<a href="/users/<%= listing.user.id %>"><%= image_tag listing.user.avatar, class: 'listing-item-avatar' %></a>
			</div>
		</div>
	</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit <%= @listing.title %></h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<div id="listing-divider">
	<div id="listing-left">
		<div id="listing-tools">
			<% if logged_in? %>
				<%= link_to (button_tag "Add new listing", class: "btn btn-block btn-large btn-pink"), new_listing_path %>
				<% if !current_user.reservations.empty? %>
					<h3 class="listing-tools-title">Your Reservations</h3>
					<% current_user.reservations.each do |reservation| %>
						<hr>
						<div class="listing-reservation">
							<div class="listing-reservation-item">
								<div class="listing-reservation-item">
									<%= image_tag reservation.listing.images[0] if !reservation.listing.images[0].nil? %>
								</div>
								<div class="listing-reservation-item">
									<%= reservation.listing.title %><br>
									<%= reservation.checkin.strftime("%e %b %Y") %> until <%= reservation.checkout.strftime("%e %b %Y") %>
								</div>
							</div>
							<div class="listing-reservation-item">
								<%= link_to (button_tag "Delete", class: "btn btn-block btn-large btn-pink"), listing_reservation_path(reservation.listing, reservation), method: 'delete' %>
							</div>						
						</div>
					<% end %>
				<% end %>
			<% end %>
			<h3 class="listing-tools-title">Filter</h3>
			<hr>
			<div class="listing-reservation-item">
				<%= form_tag filter_listings_path, id: 'filter-form', remote: true do %>
					<%= hidden_field_tag :location, @listings.first.location %>
					Price Range <%= text_field_tag :from, nil, class: 'form-control' %> to <%= text_field_tag :to, nil, class: 'form-control' %> <%= submit_tag 'Filter', class: 'btn btn-medium btn-pink', id: 'filter-btn' %>
				<% end %>
			</div>
		</div>
		<div id="listing-container">
			<div id="loading"></div>
			<% if !@listings.nil? %>
				<div id="listing-main">
					<%= render 'listing_item', object: @listings %>
				</div>
			<% else %>
				<p>No listing yet</p>
			<% end %>
		</div>
		<div class="digg_pagination">
	    <div class="page_info">
	      <%= page_entries_info @listings %>
	    </div>
	    <%= will_paginate @listings, :container => false, previous_label: "&#9664;", next_label: "&#9654;" %>
	  </div>	
	</div>
	<div id="listing-map">
		<div id="listing-map-canvas"></div>
	</div>
</div>

<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_KEY'] %>">
  </script>
  <script type="text/javascript">
    function set_map(state, city){
      var mapOptions = {
        center: new google.maps.LatLng(25.687944,-100.309403),
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("listing-map-canvas"),
      mapOptions);
      
      if(state == ""){
        address = city;
      }else{
        address = state + ',' + city;
      }

      var geocoder = new google.maps.Geocoder();

      geocoder.geocode({
        'address':address
      },
      
      function(result, status){
        if (status == google.maps.GeocoderStatus.OK){
          map.setCenter(result[0].geometry.location);

          var marker = new google.maps.Marker({
            map: map,
            position: result[0].geometry.location
          });
        }else{
          alert("Geocode was not successful for the following reason: " + status);
        }
      });
      return false;
    }

    $(document).ready(function(){
      set_map('', '<%= @listings.first.location %>');
    })
  </script>

app/views/listings/new.html.erb
<div class=header>
  
</div>
<div class="big-title">
  <div class="big-title-header caps">List Your Space</div>
  <div class="big-title-subheader">Waterbnb lets you make money renting out your place.</div>
</div>
<%= render 'form' %>

app/views/listings/price_range.js.erb
$('#listing-main').html("<%= escape_javascript(render partial: 'listing_item', object: @listings) %>");
$('.digg_pagination').html("");
$('#loading').hide();

app/views/listings/show.html.erb
<%= provide :banner, 'listing' %>
<%= provide :banner_image, @listing.images[0].url %>
<div id="sub-container">
	<div id="listing-header">
		<div class="listing-header-user center-content">
			<a href="/users/<%= @listing.user.id %>"><%= image_tag @listing.user.avatar, class: 'listing-header-avatar' %><br><%= @listing.user.name %></a>
		</div>
		<div id="listing-header-detail-container">
			<h2><%= @listing.title %></h2>
			<div class="listing-location">
				<%= @listing.location.titleize %> <i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i><i class="fa fa-star fa-color-yellow"></i>
			</div>
			<div>
				<div class="listing-header-detail center-content"><i class="fa fa-home fa-listing"></i><br><%= @listing.home_type %></div>
			</div>
			<div>
				<div class="listing-header-detail center-content"><i class="fa fa-users fa-listing"></i><br><%= pluralize @listing.guest, 'guest' %></div>
			</div>
			<div>
				<div class="listing-header-detail center-content"><i class="fa fa-bed fa-listing"></i><br><%= pluralize @listing.bedroom, 'bedroom' %></div>
			</div>
			<div>
				<div class="listing-header-detail center-content"><i class="fa fa-cutlery fa-listing"></i><br>
				<%= @listing.breakfast == true ? "Daily breakfast" : "No breakfast" %></div>
			</div>
		</div>
		<div id="listing-header-booking">
			<div id="listing-header-price">
				<span style="font-size: 1.5em;">RM<%= @listing.price %></span>
			</div>
			<div style="padding: 20px;">
				<%= render 'reservations/form_instant' %>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>


	<div id="listing-body">
		<h3>About this listing</h3>
		<p><%= @listing.description %></p>
		<div class="tags"><%= display_tags(@listing) %></div>

		<% if !current_user.nil? and current_user.id == @listing.user.id %>
			<%= link_to (button_tag "Edit", class: "btn btn-block btn-large btn-pink"), edit_listing_path(@listing) %>
			<%= link_to (button_tag "Delete", class: "btn btn-block btn-large btn-pink"), listing_path(@listing), method: 'delete' %>
		<% end %>
		<div id="listing-thumbnail">
			<% @listing.images.each_with_index do |image, index| %>
				<%= image_tag @listing.images[index].url, class: 'listing-thumbnail-image' %>
			<% end %>
		</div>
	</div>
</div>

app/views/nav/_home_nav.html.erb
<nav>
	<div class="nav-logo">
		<a href="<%= root_path %>"><%= image_tag("waterbnb_logo_white.png", size: "168x32", alt: "Waterbnb") %></a>
	</div>
	<div class="nav-home">
		<% if signed_in? %>
		  <div style="padding-top: 20px; padding-bottom: 20px;"><a href="/users/<%= current_user.id %>"><%= current_user.name %><%= image_tag current_user.avatar, class: 'avatar avatar' %></a></div>
		  <div><%= link_to 'Sign out', sign_out_path, method: :delete %></div>
		<% else %>
		  <div><%= link_to 'Log In', sign_in_path, id: 'home-login' %></div>
			<div><%= link_to 'Sign Up', sign_up_path, id: 'home-signup' %></div>
		<% end %>
		<div>Help</div>
		<div style="border-left: none;">
			<% if logged_in? && !current_user.listings.empty? %>
				<%= link_to 'Host', listings_path %>
			<% else %>
				<span class="host"><a href="<%= new_listing_path %>">Become a Host</a></span>
			<% end %>
		</div>
	</div>
	<div class="clearfix"></div>
</nav>

app/views/nav/_nav.html.erb
<nav class="nav-white">
	<div class="nav-logo nav-logo-border nav-hover">
		<a href="<%= root_path %>"><%= image_tag("waterbnb_logo.png", size: "168x32", alt: "Waterbnb") %></a>
	</div>
	<div class="nav-search">
		<form action="<%= listings_path %>">
			<input type="text"placeholder="Where are you going?" name="search">
		</form>
	</div>
	<div class="nav">
		<% if signed_in? %>
		  <div class="nav-hover" style="padding-top: 20px; padding-bottom: 20px;"><a href="/users/<%= current_user.id %>"><%= current_user.name %><%= image_tag current_user.avatar, class: 'avatar avatar' %></a></div>
		  <div class="nav-hover"><%= link_to 'Sign out', sign_out_path, method: :delete %></div>
		<% else %>
		  <div class="nav-hover"><%= link_to 'Log In', sign_in_path %></div>
			<div class="nav-hover"><%= link_to 'Sign Up', sign_up_path %></div>
		<% end %>
		<div class="nav-hover">Help</div>
		<div style="border-left: none;">
			<% if logged_in? && !current_user.listings.empty? %>
				<%= link_to 'Host', listings_path %>
			<% else %>
				<span class="host"><a href="<%= new_listing_path %>">Become a Host</a></span>
			<% end %>
		</div>
	</div>
	<div class="clearfix"></div>
</nav>

app/views/reservations/_form_instant.html.erb
<%= form_for [@listing, @reservation] do |f| %>
	<div class="reservation-container">
		<div class="reservation-item">
			<%= f.label 'Check In' %><br>
			<%= f.text_field :checkin, placeholder: 'dd/mm/yyyy', class: 'datepicker form-control full-width-80' %>
		</div>
		<div class="reservation-item">
			<%= f.label 'Check Out' %><br>
			<%= f.text_field :checkout, placeholder: 'dd/mm/yyyy', class: 'datepicker form-control full-width-80' %>
		</div>
	</div>
	<%= button_tag type: 'submit', class: 'btn btn-large btn-pink full-width' do %>
		<span class="fa fa-bolt fa-color-yellow"></span>&nbsp;&nbsp;Instant Book
	<% end %>
<% end %>

<script type="text/javascript">
	$(function(){
    $('.datepicker').datepicker({
        inline: true,
        firstDay: 1,
        dateFormat: 'dd/mm/yy',
        showOtherMonths: true,
        dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        changeMonth: true,
        changeYear: true
    });
	});
</script>

app/views/search/search.html.erb
<h1>Listing Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @listings.each do |listing| %>
    <li>
      <h3>
        <%= link_to listing.title, controller: "listings", action: "show", id: listing_id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages', object: form.object %>

<%= form.text_field :name, class: 'form-control full-width-92', placeholder: :name, required: true %>
<%= form.email_field :email, class: 'form-control full-width-92', placeholder: 'Email Address', required: true %>
<%= form.password_field :password, class: 'form-control full-width-92', placeholder: :password, required: true %>
<%= form.password_field :password_confirmation, class: 'form-control full-width-92', placeholder: :password_confirmation, required: true %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up center-layout">
  <a href="/auth/facebook" class="btn icon-btn btn-block btn-large btn-facebook"><span class="icon"><%= fa_icon "facebook" %></span>Sign up with Facebook</a>
  <hr>
  <div class="or-hr center-content">or</div>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', method: 'post', object: form %>
    <br><br>
    <small>By signing up, I agree to Waterbnb's <a href="#">Terms of Service</a>, <a href="#">Privacy Policy</a>, <a href="#">Guest Refund Policy</a>, and <a href="#">Host Guarantee Terms</a>.</small>
    <br><br>
    <%= form.submit 'Sign up', class: 'btn btn-block btn-large btn-pink full-width' %>
    <hr>
    Already a Waterbnb member? <%= link_to 'Log in', sign_in_path %>
  <% end %>
</div>